# syntax=docker/dockerfile:1.4

FROM node:22

WORKDIR /app

COPY ./repos/letta /app/letta
COPY ./repos/navigator-bots /app/navigator-bots

RUN apt-get update && apt-get install -y python3 python3-venv python3-pip
# Create and activate a virtual environment
RUN python3 -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

RUN pip install uv

WORKDIR /app/letta

RUN uv sync --all-extras

EXPOSE 8283

# CMD is now in docker-compose.yaml
